// ============================================================================
// breeds.js — Master list of dog + cat breeds for the BreedPicker dropdown
// ============================================================================
// Alphabetical, deduplicated. Includes AKC/UKC breeds plus the common
// "designer" breeds (doodles, etc.) groomers see day-to-day.
//
// Usage:
//   import { ALL_BREEDS, DOG_BREEDS, CAT_BREEDS } from '../lib/breeds'
//   <BreedPicker breeds={DOG_BREEDS} value={breed} onChange={setBreed} />
//
// "Other" / custom is handled by the BreedPicker component itself —
// don't add it to this list.
// ============================================================================

export var DOG_BREEDS = [
  'Affenpinscher',
  'Afghan Hound',
  'Airedale Terrier',
  'Akita',
  'Alaskan Klee Kai',
  'Alaskan Malamute',
  'American Bulldog',
  'American Eskimo Dog',
  'American Foxhound',
  'American Hairless Terrier',
  'American Pit Bull Terrier',
  'American Staffordshire Terrier',
  'American Water Spaniel',
  'Anatolian Shepherd',
  'Aussiedoodle',
  'Australian Cattle Dog',
  'Australian Kelpie',
  'Australian Shepherd',
  'Australian Terrier',
  'Azawakh',
  'Basenji',
  'Basset Hound',
  'Beagle',
  'Bearded Collie',
  'Beauceron',
  'Bedlington Terrier',
  'Belgian Malinois',
  'Belgian Sheepdog',
  'Belgian Tervuren',
  'Bergamasco Sheepdog',
  'Berger Picard',
  'Bernedoodle',
  'Bernese Mountain Dog',
  'Bichon Frise',
  'Black and Tan Coonhound',
  'Black Russian Terrier',
  'Bloodhound',
  'Blue Heeler',
  'Bluetick Coonhound',
  'Boerboel',
  'Bolognese',
  'Border Collie',
  'Border Terrier',
  'Borzoi',
  'Boston Terrier',
  'Bouvier des Flandres',
  'Boxer',
  'Boykin Spaniel',
  'Bracco Italiano',
  'Briard',
  'Brittany',
  'Brussels Griffon',
  'Bull Terrier',
  'Bulldog',
  'Bullmastiff',
  'Cairn Terrier',
  'Canaan Dog',
  'Cane Corso',
  'Cardigan Welsh Corgi',
  'Catahoula Leopard Dog',
  'Caucasian Shepherd',
  'Cavachon',
  'Cavalier King Charles Spaniel',
  'Cavapoo',
  'Cesky Terrier',
  'Chesapeake Bay Retriever',
  'Chihuahua',
  'Chihuahua (Long Coat)',
  'Chinese Crested',
  'Chinese Shar-Pei',
  'Chinook',
  'Chiweenie',
  'Chow Chow',
  'Cirneco dell\'Etna',
  'Clumber Spaniel',
  'Cockapoo',
  'Cocker Spaniel',
  'Collie',
  'Coton de Tulear',
  'Curly-Coated Retriever',
  'Dachshund',
  'Dachshund (Long-Haired)',
  'Dachshund (Wire-Haired)',
  'Dalmatian',
  'Dandie Dinmont Terrier',
  'Doberman Pinscher',
  'Dogo Argentino',
  'Dogue de Bordeaux',
  'Dutch Shepherd',
  'English Bulldog',
  'English Cocker Spaniel',
  'English Foxhound',
  'English Mastiff',
  'English Setter',
  'English Springer Spaniel',
  'English Toy Spaniel',
  'Entlebucher Mountain Dog',
  'Eurasier',
  'Field Spaniel',
  'Finnish Lapphund',
  'Finnish Spitz',
  'Flat-Coated Retriever',
  'Fox Terrier (Smooth)',
  'Fox Terrier (Wire)',
  'French Bulldog',
  'German Pinscher',
  'German Shepherd',
  'German Shorthaired Pointer',
  'German Wirehaired Pointer',
  'Giant Schnauzer',
  'Glen of Imaal Terrier',
  'Goldador',
  'Golden Retriever',
  'Goldendoodle',
  'Gordon Setter',
  'Great Dane',
  'Great Pyrenees',
  'Greater Swiss Mountain Dog',
  'Greyhound',
  'Hairless Chinese Crested',
  'Harrier',
  'Havanese',
  'Hovawart',
  'Ibizan Hound',
  'Icelandic Sheepdog',
  'Irish Doodle',
  'Irish Red and White Setter',
  'Irish Setter',
  'Irish Terrier',
  'Irish Water Spaniel',
  'Irish Wolfhound',
  'Italian Greyhound',
  'Jack Russell Terrier',
  'Japanese Chin',
  'Japanese Spitz',
  'Karelian Bear Dog',
  'Keeshond',
  'Kerry Blue Terrier',
  'King Charles Spaniel',
  'Komondor',
  'Kooikerhondje',
  'Kuvasz',
  'Labradoodle',
  'Labrador Retriever',
  'Lagotto Romagnolo',
  'Lakeland Terrier',
  'Lancashire Heeler',
  'Leonberger',
  'Lhasa Apso',
  'Lowchen',
  'Maltese',
  'Maltipoo',
  'Manchester Terrier',
  'Maremma Sheepdog',
  'Mastiff',
  'Miniature American Shepherd',
  'Miniature Australian Shepherd',
  'Miniature Bull Terrier',
  'Miniature Dachshund',
  'Miniature Goldendoodle',
  'Miniature Labradoodle',
  'Miniature Pinscher',
  'Miniature Poodle',
  'Miniature Schnauzer',
  'Mixed Breed',
  'Morkie',
  'Mountain Cur',
  'Mudi',
  'Mutt',
  'Neapolitan Mastiff',
  'Newfoundland',
  'Norfolk Terrier',
  'Norrbottenspets',
  'Norwegian Buhund',
  'Norwegian Elkhound',
  'Norwegian Lundehund',
  'Norwich Terrier',
  'Nova Scotia Duck Tolling Retriever',
  'Old English Sheepdog',
  'Otterhound',
  'Papillon',
  'Pekingese',
  'Pembroke Welsh Corgi',
  'Petit Basset Griffon Vendeen',
  'Pharaoh Hound',
  'Pit Bull',
  'Plott Hound',
  'Pointer',
  'Polish Lowland Sheepdog',
  'Pomeranian',
  'Pomsky',
  'Poodle (Standard)',
  'Poodle (Toy)',
  'Portuguese Podengo',
  'Portuguese Water Dog',
  'Pug',
  'Puggle',
  'Puli',
  'Pumi',
  'Pyrenean Shepherd',
  'Rat Terrier',
  'Redbone Coonhound',
  'Rhodesian Ridgeback',
  'Rottweiler',
  'Russian Toy',
  'Saint Bernard',
  'Saluki',
  'Samoyed',
  'Schipperke',
  'Schnauzer (Standard)',
  'Schnoodle',
  'Scottish Deerhound',
  'Scottish Terrier',
  'Sealyham Terrier',
  'Sheepadoodle',
  'Shetland Sheepdog',
  'Shiba Inu',
  'Shih Tzu',
  'Shih-Poo',
  'Shiloh Shepherd',
  'Siberian Husky',
  'Silky Terrier',
  'Skye Terrier',
  'Sloughi',
  'Small Munsterlander',
  'Soft Coated Wheaten Terrier',
  'Spanish Water Dog',
  'Spinone Italiano',
  'Staffordshire Bull Terrier',
  'Standard Poodle',
  'Standard Schnauzer',
  'Sussex Spaniel',
  'Swedish Vallhund',
  'Teddy Bear',
  'Thai Ridgeback',
  'Tibetan Mastiff',
  'Tibetan Spaniel',
  'Tibetan Terrier',
  'Toy Fox Terrier',
  'Toy Poodle',
  'Treeing Tennessee Brindle',
  'Treeing Walker Coonhound',
  'Vizsla',
  'Weimaraner',
  'Welsh Springer Spaniel',
  'Welsh Terrier',
  'West Highland White Terrier',
  'Whippet',
  'Wire Fox Terrier',
  'Wirehaired Pointing Griffon',
  'Wirehaired Vizsla',
  'Xoloitzcuintli',
  'Yorkie-Poo',
  'Yorkshire Terrier',
]

export var CAT_BREEDS = [
  'Abyssinian',
  'American Bobtail',
  'American Curl',
  'American Shorthair',
  'American Wirehair',
  'Balinese',
  'Bengal',
  'Birman',
  'Bombay',
  'British Longhair',
  'British Shorthair',
  'Burmese',
  'Burmilla',
  'Chartreux',
  'Cornish Rex',
  'Devon Rex',
  'Domestic Longhair',
  'Domestic Medium Hair',
  'Domestic Shorthair',
  'Egyptian Mau',
  'Exotic Shorthair',
  'Havana Brown',
  'Himalayan',
  'Japanese Bobtail',
  'Javanese',
  'Korat',
  'LaPerm',
  'Maine Coon',
  'Manx',
  'Mixed Breed Cat',
  'Munchkin',
  'Nebelung',
  'Norwegian Forest Cat',
  'Ocicat',
  'Oriental Shorthair',
  'Persian',
  'Peterbald',
  'Pixie-Bob',
  'Ragamuffin',
  'Ragdoll',
  'Russian Blue',
  'Savannah',
  'Scottish Fold',
  'Selkirk Rex',
  'Siamese',
  'Siberian',
  'Singapura',
  'Snowshoe',
  'Somali',
  'Sphynx',
  'Tonkinese',
  'Toyger',
  'Turkish Angora',
  'Turkish Van',
]

// Combined list — alphabetical across both species. Used by forms that
// don't know upfront whether the pet is a dog or a cat.
export var ALL_BREEDS = [].concat(DOG_BREEDS, CAT_BREEDS).sort(function (a, b) {
  return a.toLowerCase().localeCompare(b.toLowerCase())
})
