// ==========================================
// ROLE DEFAULT PERMISSIONS
// Shared across usePermissions hook and StaffDetail page
// ==========================================

var ROLE_DEFAULTS = {
  owner: {
    'calendar.view_own': true, 'calendar.view_all': true,
    'calendar.create_own': true, 'calendar.create_others': true,
    'calendar.edit_own': true, 'calendar.edit_others': true,
    'calendar.delete': true, 'calendar.override_capacity': true,
    'calendar.set_hours_own': true, 'calendar.set_hours_others': true,
    'clients.view_list': true, 'clients.view_profile': true,
    'clients.add': true, 'clients.edit': true, 'clients.delete': true,
    'clients.email': true, 'clients.sms': true,
    'pets.add_edit': true, 'pets.view_medical': true, 'pets.edit_medical': true,
    'notes.add_grooming': true, 'notes.add_client': true,
    'notes.view': true, 'notes.delete': true,
    'boarding.view_calendar': true, 'boarding.create': true,
    'boarding.edit': true, 'boarding.cancel': true,
    'boarding.log_welfare': true, 'boarding.view_welfare': true,
    'boarding.print_kennel': true, 'boarding.manage_runs': true,
    'boarding.override_capacity': true, 'boarding.daycare_checkin': true,
    'vaccines.view': true, 'vaccines.add_edit': true,
    'vaccines.override_expired': true, 'vaccines.manage_required': true,
    'pricing.view': true, 'pricing.edit_prices': true,
    'pricing.add_edit_services': true, 'pricing.process_payment': true,
    'pricing.refund': true, 'pricing.view_revenue': true,
    'pricing.view_own_sales': true, 'pricing.view_all_sales': true,
    'pricing.apply_discount': true, 'pricing.override_price': true,
    'pricing.cash_drawer': true,
    'staff.view_list': true, 'staff.add': true,
    'staff.edit_profiles': true, 'staff.deactivate': true,
    'staff.change_roles': true, 'staff.toggle_permissions': true,
    'staff.view_payroll': true, 'staff.edit_payroll': true,
    'staff.clock_own': true, 'staff.view_others_clock': true,
    'staff.edit_time': true,
    'ai.trigger_validation': true, 'ai.view_flags': true,
    'ai.override_warnings': true, 'ai.access_settings': true,
    'ai.voice_booking': true,
    'settings.edit_business': true, 'settings.manage_billing': true,
    'settings.import_export': true, 'settings.view_audit': true,
    'settings.notifications_biz': true, 'settings.notifications_own': true,
    'settings.client_portal': true,
  },
  manager: {
    'calendar.view_own': true, 'calendar.view_all': true,
    'calendar.create_own': true, 'calendar.create_others': true,
    'calendar.edit_own': true, 'calendar.edit_others': true,
    'calendar.delete': true, 'calendar.override_capacity': true,
    'calendar.set_hours_own': true, 'calendar.set_hours_others': true,
    'clients.view_list': true, 'clients.view_profile': true,
    'clients.add': true, 'clients.edit': true, 'clients.delete': true,
    'clients.email': true, 'clients.sms': true,
    'pets.add_edit': true, 'pets.view_medical': true, 'pets.edit_medical': true,
    'notes.add_grooming': true, 'notes.add_client': true,
    'notes.view': true, 'notes.delete': true,
    'boarding.view_calendar': true, 'boarding.create': true,
    'boarding.edit': true, 'boarding.cancel': true,
    'boarding.log_welfare': true, 'boarding.view_welfare': true,
    'boarding.print_kennel': true, 'boarding.manage_runs': true,
    'boarding.override_capacity': true, 'boarding.daycare_checkin': true,
    'vaccines.view': true, 'vaccines.add_edit': true,
    'vaccines.override_expired': true, 'vaccines.manage_required': true,
    'pricing.view': true, 'pricing.edit_prices': true,
    'pricing.add_edit_services': true, 'pricing.process_payment': true,
    'pricing.refund': true, 'pricing.view_revenue': true,
    'pricing.view_own_sales': true, 'pricing.view_all_sales': true,
    'pricing.apply_discount': true, 'pricing.override_price': true,
    'pricing.cash_drawer': true,
    'staff.view_list': true, 'staff.add': true,
    'staff.edit_profiles': true, 'staff.deactivate': false,
    'staff.change_roles': false, 'staff.toggle_permissions': true,
    'staff.view_payroll': true, 'staff.edit_payroll': false,
    'staff.clock_own': true, 'staff.view_others_clock': true,
    'staff.edit_time': true,
    'ai.trigger_validation': true, 'ai.view_flags': true,
    'ai.override_warnings': true, 'ai.access_settings': true,
    'ai.voice_booking': true,
    'settings.edit_business': true, 'settings.manage_billing': false,
    'settings.import_export': true, 'settings.view_audit': true,
    'settings.notifications_biz': true, 'settings.notifications_own': true,
    'settings.client_portal': true,
  },
  groomer: {
    'calendar.view_own': true, 'calendar.view_all': false,
    'calendar.create_own': true, 'calendar.create_others': false,
    'calendar.edit_own': true, 'calendar.edit_others': false,
    'calendar.delete': false, 'calendar.override_capacity': false,
    'calendar.set_hours_own': true, 'calendar.set_hours_others': false,
    'clients.view_list': true, 'clients.view_profile': true,
    'clients.add': false, 'clients.edit': false, 'clients.delete': false,
    'clients.email': false, 'clients.sms': false,
    'pets.add_edit': true, 'pets.view_medical': true, 'pets.edit_medical': true,
    'notes.add_grooming': true, 'notes.add_client': true,
    'notes.view': true, 'notes.delete': false,
    'boarding.view_calendar': false, 'boarding.create': false,
    'boarding.edit': false, 'boarding.cancel': false,
    'boarding.log_welfare': false, 'boarding.view_welfare': false,
    'boarding.print_kennel': false, 'boarding.manage_runs': false,
    'boarding.override_capacity': false, 'boarding.daycare_checkin': false,
    'vaccines.view': true, 'vaccines.add_edit': false,
    'vaccines.override_expired': false, 'vaccines.manage_required': false,
    'pricing.view': true, 'pricing.edit_prices': false,
    'pricing.add_edit_services': false, 'pricing.process_payment': false,
    'pricing.refund': false, 'pricing.view_revenue': false,
    'pricing.view_own_sales': true, 'pricing.view_all_sales': false,
    'pricing.apply_discount': false, 'pricing.override_price': false,
    'pricing.cash_drawer': false,
    'staff.view_list': false, 'staff.add': false,
    'staff.edit_profiles': false, 'staff.deactivate': false,
    'staff.change_roles': false, 'staff.toggle_permissions': false,
    'staff.view_payroll': false, 'staff.edit_payroll': false,
    'staff.clock_own': true, 'staff.view_others_clock': false,
    'staff.edit_time': false,
    'ai.trigger_validation': true, 'ai.view_flags': true,
    'ai.override_warnings': false, 'ai.access_settings': false,
    'ai.voice_booking': true,
    'settings.edit_business': false, 'settings.manage_billing': false,
    'settings.import_export': false, 'settings.view_audit': false,
    'settings.notifications_biz': false, 'settings.notifications_own': true,
    'settings.client_portal': false,
  },
  bather: {
    'calendar.view_own': true, 'calendar.view_all': false,
    'calendar.create_own': false, 'calendar.create_others': false,
    'calendar.edit_own': false, 'calendar.edit_others': false,
    'calendar.delete': false, 'calendar.override_capacity': false,
    'calendar.set_hours_own': true, 'calendar.set_hours_others': false,
    'clients.view_list': true, 'clients.view_profile': true,
    'clients.add': false, 'clients.edit': false, 'clients.delete': false,
    'clients.email': false, 'clients.sms': false,
    'pets.add_edit': false, 'pets.view_medical': true, 'pets.edit_medical': false,
    'notes.add_grooming': true, 'notes.add_client': false,
    'notes.view': true, 'notes.delete': false,
    'boarding.view_calendar': false, 'boarding.create': false,
    'boarding.edit': false, 'boarding.cancel': false,
    'boarding.log_welfare': false, 'boarding.view_welfare': false,
    'boarding.print_kennel': false, 'boarding.manage_runs': false,
    'boarding.override_capacity': false, 'boarding.daycare_checkin': false,
    'vaccines.view': true, 'vaccines.add_edit': false,
    'vaccines.override_expired': false, 'vaccines.manage_required': false,
    'pricing.view': true, 'pricing.edit_prices': false,
    'pricing.add_edit_services': false, 'pricing.process_payment': false,
    'pricing.refund': false, 'pricing.view_revenue': false,
    'pricing.view_own_sales': true, 'pricing.view_all_sales': false,
    'pricing.apply_discount': false, 'pricing.override_price': false,
    'pricing.cash_drawer': false,
    'staff.view_list': false, 'staff.add': false,
    'staff.edit_profiles': false, 'staff.deactivate': false,
    'staff.change_roles': false, 'staff.toggle_permissions': false,
    'staff.view_payroll': false, 'staff.edit_payroll': false,
    'staff.clock_own': true, 'staff.view_others_clock': false,
    'staff.edit_time': false,
    'ai.trigger_validation': false, 'ai.view_flags': false,
    'ai.override_warnings': false, 'ai.access_settings': false,
    'ai.voice_booking': false,
    'settings.edit_business': false, 'settings.manage_billing': false,
    'settings.import_export': false, 'settings.view_audit': false,
    'settings.notifications_biz': false, 'settings.notifications_own': true,
    'settings.client_portal': false,
  },
  kennel_tech: {
    'calendar.view_own': true, 'calendar.view_all': false,
    'calendar.create_own': false, 'calendar.create_others': false,
    'calendar.edit_own': false, 'calendar.edit_others': false,
    'calendar.delete': false, 'calendar.override_capacity': false,
    'calendar.set_hours_own': true, 'calendar.set_hours_others': false,
    'clients.view_list': true, 'clients.view_profile': true,
    'clients.add': false, 'clients.edit': false, 'clients.delete': false,
    'clients.email': false, 'clients.sms': false,
    'pets.add_edit': false, 'pets.view_medical': true, 'pets.edit_medical': false,
    'notes.add_grooming': false, 'notes.add_client': false,
    'notes.view': true, 'notes.delete': false,
    'boarding.view_calendar': true, 'boarding.create': false,
    'boarding.edit': false, 'boarding.cancel': false,
    'boarding.log_welfare': true, 'boarding.view_welfare': true,
    'boarding.print_kennel': true, 'boarding.manage_runs': true,
    'boarding.override_capacity': false, 'boarding.daycare_checkin': true,
    'vaccines.view': true, 'vaccines.add_edit': false,
    'vaccines.override_expired': false, 'vaccines.manage_required': false,
    'pricing.view': false, 'pricing.edit_prices': false,
    'pricing.add_edit_services': false, 'pricing.process_payment': false,
    'pricing.refund': false, 'pricing.view_revenue': false,
    'pricing.view_own_sales': false, 'pricing.view_all_sales': false,
    'pricing.apply_discount': false, 'pricing.override_price': false,
    'pricing.cash_drawer': false,
    'staff.view_list': false, 'staff.add': false,
    'staff.edit_profiles': false, 'staff.deactivate': false,
    'staff.change_roles': false, 'staff.toggle_permissions': false,
    'staff.view_payroll': false, 'staff.edit_payroll': false,
    'staff.clock_own': true, 'staff.view_others_clock': false,
    'staff.edit_time': false,
    'ai.trigger_validation': false, 'ai.view_flags': false,
    'ai.override_warnings': false, 'ai.access_settings': false,
    'ai.voice_booking': false,
    'settings.edit_business': false, 'settings.manage_billing': false,
    'settings.import_export': false, 'settings.view_audit': false,
    'settings.notifications_biz': false, 'settings.notifications_own': true,
    'settings.client_portal': false,
  },
  front_desk: {
    'calendar.view_own': true, 'calendar.view_all': true,
    'calendar.create_own': true, 'calendar.create_others': true,
    'calendar.edit_own': true, 'calendar.edit_others': true,
    'calendar.delete': true, 'calendar.override_capacity': false,
    'calendar.set_hours_own': true, 'calendar.set_hours_others': false,
    'clients.view_list': true, 'clients.view_profile': true,
    'clients.add': true, 'clients.edit': true, 'clients.delete': false,
    'clients.email': true, 'clients.sms': true,
    'pets.add_edit': true, 'pets.view_medical': true, 'pets.edit_medical': true,
    'notes.add_grooming': false, 'notes.add_client': true,
    'notes.view': true, 'notes.delete': false,
    'boarding.view_calendar': true, 'boarding.create': true,
    'boarding.edit': true, 'boarding.cancel': true,
    'boarding.log_welfare': false, 'boarding.view_welfare': true,
    'boarding.print_kennel': true, 'boarding.manage_runs': true,
    'boarding.override_capacity': false, 'boarding.daycare_checkin': true,
    'vaccines.view': true, 'vaccines.add_edit': true,
    'vaccines.override_expired': false, 'vaccines.manage_required': false,
    'pricing.view': true, 'pricing.edit_prices': false,
    'pricing.add_edit_services': false, 'pricing.process_payment': true,
    'pricing.refund': false, 'pricing.view_revenue': false,
    'pricing.view_own_sales': true, 'pricing.view_all_sales': false,
    'pricing.apply_discount': true, 'pricing.override_price': false,
    'pricing.cash_drawer': true,
    'staff.view_list': true, 'staff.add': false,
    'staff.edit_profiles': false, 'staff.deactivate': false,
    'staff.change_roles': false, 'staff.toggle_permissions': false,
    'staff.view_payroll': false, 'staff.edit_payroll': false,
    'staff.clock_own': true, 'staff.view_others_clock': false,
    'staff.edit_time': false,
    'ai.trigger_validation': true, 'ai.view_flags': true,
    'ai.override_warnings': false, 'ai.access_settings': false,
    'ai.voice_booking': true,
    'settings.edit_business': false, 'settings.manage_billing': false,
    'settings.import_export': false, 'settings.view_audit': false,
    'settings.notifications_biz': false, 'settings.notifications_own': true,
    'settings.client_portal': false,
  },
  trainer: {
    'calendar.view_own': true, 'calendar.view_all': false,
    'calendar.create_own': true, 'calendar.create_others': false,
    'calendar.edit_own': true, 'calendar.edit_others': false,
    'calendar.delete': false, 'calendar.override_capacity': false,
    'calendar.set_hours_own': true, 'calendar.set_hours_others': false,
    'clients.view_list': true, 'clients.view_profile': true,
    'clients.add': false, 'clients.edit': false, 'clients.delete': false,
    'clients.email': false, 'clients.sms': false,
    'pets.add_edit': false, 'pets.view_medical': true, 'pets.edit_medical': false,
    'notes.add_grooming': false, 'notes.add_client': false,
    'notes.view': true, 'notes.delete': false,
    'boarding.view_calendar': false, 'boarding.create': false,
    'boarding.edit': false, 'boarding.cancel': false,
    'boarding.log_welfare': false, 'boarding.view_welfare': false,
    'boarding.print_kennel': false, 'boarding.manage_runs': false,
    'boarding.override_capacity': false, 'boarding.daycare_checkin': false,
    'vaccines.view': true, 'vaccines.add_edit': false,
    'vaccines.override_expired': false, 'vaccines.manage_required': false,
    'pricing.view': false, 'pricing.edit_prices': false,
    'pricing.add_edit_services': false, 'pricing.process_payment': false,
    'pricing.refund': false, 'pricing.view_revenue': false,
    'pricing.view_own_sales': false, 'pricing.view_all_sales': false,
    'pricing.apply_discount': false, 'pricing.override_price': false,
    'pricing.cash_drawer': false,
    'staff.view_list': false, 'staff.add': false,
    'staff.edit_profiles': false, 'staff.deactivate': false,
    'staff.change_roles': false, 'staff.toggle_permissions': false,
    'staff.view_payroll': false, 'staff.edit_payroll': false,
    'staff.clock_own': true, 'staff.view_others_clock': false,
    'staff.edit_time': false,
    'ai.trigger_validation': false, 'ai.view_flags': false,
    'ai.override_warnings': false, 'ai.access_settings': false,
    'ai.voice_booking': false,
    'settings.edit_business': false, 'settings.manage_billing': false,
    'settings.import_export': false, 'settings.view_audit': false,
    'settings.notifications_biz': false, 'settings.notifications_own': true,
    'settings.client_portal': false,
  },
}

export default ROLE_DEFAULTS
